[package]
name = "gas"
edition = "2024"
version.workspace = true
authors.workspace = true
rust-version.workspace = true
readme.workspace = true

[lib]
name = "gas"

[dependencies]
common = { path = "../common"}
macros = { path = "../macros" }